# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
#    - name: Test Report0
#      if: ${{ always() }}
#      uses: scacap/action-surefire-report@v1
#      with:
#        check_name: Failed Tests Report
#        report_paths: '**/surefire-reports/*.xml'

    - name: Test Report2
      uses: dorny/test-reporter@v1.5.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Full Test Report          # Name of the check run which will be created
        path: '**/surefire-reports/*.xml'    # Path to test results
        reporter: java-junit        # Format of test results
